services:
  - type: web
    name: ypdlp
    runtime: python
    buildCommand: pip install -U -r requirements.txt
    startCommand: gunicorn server:app --bind 0.0.0.0:$PORT --workers 1 --threads 4 --timeout 120 --keep-alive 5
    rootDir: website
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
    plan: free
